### NUMPY

In [11]:
import numpy as np


In [12]:
np.array(["mario",2,3])  # List to array

array(['mario', '2', '3'], dtype='<U5')

In [13]:
np.array([[1,2],[3,4]])  # array[[i1,j1][i2,j2]] 2D

array([[1, 2],
       [3, 4]])

In [14]:
np.array([1,2,3], ndmin=5)  # 5D array

array([[[[[1, 2, 3]]]]])

In [15]:
np.array([1,2,3], dtype=complex)  # dtype

array([1.+0.j, 2.+0.j, 3.+0.j])

In [16]:
np.array([(1,2),(3,4)],dtype=[('a','<i2'),('b','<i8')]) # list of tuples into an array (a,b)
                                                        # <i2 integer16, <i8 = int64

array([(1, 2), (3, 4)], dtype=[('a', '<i2'), ('b', '<i8')])

In [18]:
n = np.array([[1,2],[3,4]])
n

array([[1, 2],
       [3, 4]])

In [19]:
n[0]

array([1, 2])

In [20]:
n[1][1]


4

### create an array from sub-classes:

In [22]:
np.mat(np.array([(1,2),(3,4)]))  # matrixes are a subclass of arrays

matrix([[1, 2],
        [3, 4]])

In [23]:
np.mat('1 2; 3 4')

matrix([[1, 2],
        [3, 4]])

In [24]:
a=[1,2]
np.asarray(a)

array([1, 2])

### asanyarray - converts into an array if the data is not in an array format

### np.array(A), np.asarray(A) both convert A into an array type 
### np.asanyarray(A) - converts A into an array type only if A is not an array already, otherwise does nothing

In [26]:
a = [1,2]
np.asanyarray(a)  # it converts to an array if a is not array, otherwise does nothing

array([1, 2])

In [29]:
a = np.matrix([1,2])
a

matrix([[1, 2]])

In [30]:
np.asanyarray(a)  # does nothing since a is already an matrix - subclass of an array.

matrix([[1, 2]])

In [31]:
a

matrix([[1, 2]])

In [32]:
np.array(a)  # converts a which is matrix into an array

array([[1, 2]])

In [33]:
np.asanyarray(a)  # does nothing since a is already an matrix - subclass of an array.

matrix([[1, 2]])

In [34]:
np.asarray(a) # converts a which is matrix into an array

array([[1, 2]])

### numpy.fromfunction - consturct an array by executing a function over each coordinate

In [38]:
np.fromfunction(lambda i, j: i==j, (3,3), dtype=int)

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [39]:
np.fromfunction(lambda i, j: i*j, (3,3), dtype=int)

array([[0, 0, 0],
       [0, 1, 2],
       [0, 2, 4]])

### fromiter - use a iterable object into an array

In [43]:
iterable = (x*x for x in range(5))
iterable

<generator object <genexpr> at 0x000001B0F3F6F990>

In [44]:
np.fromiter(iterable, float)

array([ 0.,  1.,  4.,  9., 16.])

In [45]:
np.fromstring('1, 2', dtype=int, sep=',')

array([1, 2])

## Data Types

In [57]:
import numpy as np
my_list = [1,2,3]
arr = np.array(my_list)
print(type(arr))
print("-"*25)
print(arr)


<class 'numpy.ndarray'>
-------------------------
[1 2 3]


In [62]:
my_list = [[1,2,3],[4,5,6],[7,8,9]]
arr = np.array(my_list)
print(type(arr))
print("-"*25)
print(arr)
print("Dimensions:", arr.ndim, sep='')
print("Size:", arr.size, sep='')
print("Shape:", arr.shape, sep='')
print("Data Type:", arr.dtype, sep='')

<class 'numpy.ndarray'>
-------------------------
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Dimensions:2
Size:9
Shape:(3, 3)
Data Type:int32


### Arange and Linspace

In [63]:
list(range(4,10))   # range functions always delas with inter data

[4, 5, 6, 7, 8, 9]

In [66]:
(np.arange(4,10))

array([4, 5, 6, 7, 8, 9])

In [67]:
(np.arange(4.5,10))  # numpy arange function works with floats without issues

array([4.5, 5.5, 6.5, 7.5, 8.5, 9.5])