### NUMPY

In [1]:
import numpy as np


In [2]:
np.array(["mario",2,3])  # List to array

array(['mario', '2', '3'], dtype='<U5')

In [3]:
np.array([[1,2],[3,4]])  # array[[i1,j1][i2,j2]] 2D

array([[1, 2],
       [3, 4]])

In [4]:
np.array([1,2,3], ndmin=5)  # 5D array

array([[[[[1, 2, 3]]]]])

In [5]:
np.array([1,2,3], dtype=complex)  # dtype

array([1.+0.j, 2.+0.j, 3.+0.j])

In [6]:
np.array([(1,2),(3,4)],dtype=[('a','<i2'),('b','<i8')]) # list of tuples into an array (a,b)
                                                        # <i2 integer16, <i8 = int64

array([(1, 2), (3, 4)], dtype=[('a', '<i2'), ('b', '<i8')])

In [7]:
n = np.array([[1,2],[3,4]])
n

array([[1, 2],
       [3, 4]])

In [8]:
n[0]

array([1, 2])

In [9]:
n[1][1]


4

### create an array from sub-classes:

In [10]:
np.mat(np.array([(1,2),(3,4)]))  # matrixes are a subclass of arrays

matrix([[1, 2],
        [3, 4]])

In [11]:
np.mat('1 2; 3 4')

matrix([[1, 2],
        [3, 4]])

In [12]:
a=[1,2]
np.asarray(a)

array([1, 2])

### asanyarray - converts into an array if the data is not in an array format

### np.array(A), np.asarray(A) both convert A into an array type 
### np.asanyarray(A) - converts A into an array type only if A is not an array already, otherwise does nothing

In [13]:
a = [1,2]
np.asanyarray(a)  # it converts to an array if a is not array, otherwise does nothing

array([1, 2])

In [14]:
a = np.matrix([1,2])
a

matrix([[1, 2]])

In [15]:
np.asanyarray(a)  # does nothing since a is already an matrix - subclass of an array.

matrix([[1, 2]])

In [16]:
a

matrix([[1, 2]])

In [17]:
np.array(a)  # converts a which is matrix into an array

array([[1, 2]])

In [18]:
np.asanyarray(a)  # does nothing since a is already an matrix - subclass of an array.

matrix([[1, 2]])

In [19]:
np.asarray(a) # converts a which is matrix into an array

array([[1, 2]])

### numpy.fromfunction - consturct an array by executing a function over each coordinate

In [20]:
np.fromfunction(lambda i, j: i==j, (3,3), dtype=int)

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [21]:
np.fromfunction(lambda i, j: i*j, (3,3), dtype=int)

array([[0, 0, 0],
       [0, 1, 2],
       [0, 2, 4]])

### fromiter - use a iterable object into an array

In [22]:
iterable = (x*x for x in range(5))
iterable

<generator object <genexpr> at 0x0000023603594360>

In [23]:
np.fromiter(iterable, float)

array([ 0.,  1.,  4.,  9., 16.])

In [24]:
np.fromstring('1, 2', dtype=int, sep=',')

array([1, 2])

## Data Types

In [25]:
import numpy as np
my_list = [1,2,3]
arr = np.array(my_list)
print(type(arr))
print("-"*25)
print(arr)


<class 'numpy.ndarray'>
-------------------------
[1 2 3]


In [26]:
my_list = [[1,2,3],[4,5,6],[7,8,9]]
arr = np.array(my_list)
print(type(arr))
print("-"*25)
print(arr)
print("Dimensions:", arr.ndim, sep='')
print("Size:", arr.size, sep='')
print("Shape:", arr.shape, sep='')
print("Data Type:", arr.dtype, sep='')

<class 'numpy.ndarray'>
-------------------------
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Dimensions:2
Size:9
Shape:(3, 3)
Data Type:int32


### Arange and Linspace

In [30]:
range(4,10)

range(4, 10)

In [27]:
list(range(4,10))   # range functions always delas with inter data

[4, 5, 6, 7, 8, 9]

In [28]:
(np.arange(4,10))

array([4, 5, 6, 7, 8, 9])

In [29]:
(np.arange(4.5,10))  # numpy arange function works with floats without issues

array([4.5, 5.5, 6.5, 7.5, 8.5, 9.5])

In [31]:
np.linspace(1,5,50)

array([1.        , 1.08163265, 1.16326531, 1.24489796, 1.32653061,
       1.40816327, 1.48979592, 1.57142857, 1.65306122, 1.73469388,
       1.81632653, 1.89795918, 1.97959184, 2.06122449, 2.14285714,
       2.2244898 , 2.30612245, 2.3877551 , 2.46938776, 2.55102041,
       2.63265306, 2.71428571, 2.79591837, 2.87755102, 2.95918367,
       3.04081633, 3.12244898, 3.20408163, 3.28571429, 3.36734694,
       3.44897959, 3.53061224, 3.6122449 , 3.69387755, 3.7755102 ,
       3.85714286, 3.93877551, 4.02040816, 4.10204082, 4.18367347,
       4.26530612, 4.34693878, 4.42857143, 4.51020408, 4.59183673,
       4.67346939, 4.75510204, 4.83673469, 4.91836735, 5.        ])

In [32]:
np.zeros(5)  # vector of zeroes

array([0., 0., 0., 0., 0.])

In [33]:
np.zeros((3,4))  # matrix of zeroes

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [35]:
np.zeros((3,4,2))  # matrix of zeroes, 3 matrixes (4,2)

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [34]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [36]:
np.eye(4)  # matrix 4x4 diagonal value only, always a square matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [42]:
np.empty((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [44]:
np.linspace(2.0,3.0, num=5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [45]:
np.linspace(2.0,3.0, num=5, retstep=True)

(array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25)

In [47]:
np.logspace(2.0,3.0,num=4)

array([ 100.        ,  215.443469  ,  464.15888336, 1000.        ])

In [48]:
np.logspace(2.0,3.0,num=4,base=5)

array([ 25.        ,  42.74939867,  73.10044346, 125.        ])

In [49]:
np.arange(16)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [57]:
np.arange(16).reshape(2,8)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [58]:
np.arange(16).reshape(-1,8)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [60]:
np.arange(16).reshape(2,8).ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [63]:
a = np.arange(24)
print(np.reshape(a, [4, 6], 'C'))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [65]:
print(np.reshape(a, [8, -1], 'C'))  # The length of the dimension set to -1 is automatically 
                                    # determined by inferring from the specified values of other dimensions. 

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]


In [68]:
np.zeros((3,4,8))+5*2

array([[[10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.]],

       [[10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.]],

       [[10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.]]])

In [75]:
np.linspace(4,8,80)

array([4.        , 4.05063291, 4.10126582, 4.15189873, 4.20253165,
       4.25316456, 4.30379747, 4.35443038, 4.40506329, 4.4556962 ,
       4.50632911, 4.55696203, 4.60759494, 4.65822785, 4.70886076,
       4.75949367, 4.81012658, 4.86075949, 4.91139241, 4.96202532,
       5.01265823, 5.06329114, 5.11392405, 5.16455696, 5.21518987,
       5.26582278, 5.3164557 , 5.36708861, 5.41772152, 5.46835443,
       5.51898734, 5.56962025, 5.62025316, 5.67088608, 5.72151899,
       5.7721519 , 5.82278481, 5.87341772, 5.92405063, 5.97468354,
       6.02531646, 6.07594937, 6.12658228, 6.17721519, 6.2278481 ,
       6.27848101, 6.32911392, 6.37974684, 6.43037975, 6.48101266,
       6.53164557, 6.58227848, 6.63291139, 6.6835443 , 6.73417722,
       6.78481013, 6.83544304, 6.88607595, 6.93670886, 6.98734177,
       7.03797468, 7.08860759, 7.13924051, 7.18987342, 7.24050633,
       7.29113924, 7.34177215, 7.39240506, 7.44303797, 7.49367089,
       7.5443038 , 7.59493671, 7.64556962, 7.69620253, 7.74683

In [77]:
np.matrix(np.linspace(4,8,80))

matrix([[4.        , 4.05063291, 4.10126582, 4.15189873, 4.20253165,
         4.25316456, 4.30379747, 4.35443038, 4.40506329, 4.4556962 ,
         4.50632911, 4.55696203, 4.60759494, 4.65822785, 4.70886076,
         4.75949367, 4.81012658, 4.86075949, 4.91139241, 4.96202532,
         5.01265823, 5.06329114, 5.11392405, 5.16455696, 5.21518987,
         5.26582278, 5.3164557 , 5.36708861, 5.41772152, 5.46835443,
         5.51898734, 5.56962025, 5.62025316, 5.67088608, 5.72151899,
         5.7721519 , 5.82278481, 5.87341772, 5.92405063, 5.97468354,
         6.02531646, 6.07594937, 6.12658228, 6.17721519, 6.2278481 ,
         6.27848101, 6.32911392, 6.37974684, 6.43037975, 6.48101266,
         6.53164557, 6.58227848, 6.63291139, 6.6835443 , 6.73417722,
         6.78481013, 6.83544304, 6.88607595, 6.93670886, 6.98734177,
         7.03797468, 7.08860759, 7.13924051, 7.18987342, 7.24050633,
         7.29113924, 7.34177215, 7.39240506, 7.44303797, 7.49367089,
         7.5443038 , 7.59493671, 7

In [86]:
a = np.empty((4,5,2))*0+1

In [88]:
print("-"*25)
print(a)
print("Dimensions:", a.ndim, sep='')
print("Size:", a.size, sep='')
print("Shape:", a.shape, sep='')
print("Data Type:", a.dtype, sep='')

-------------------------
[[[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]]
Dimensions:3
Size:40
Shape:(4, 5, 2)
Data Type:float64


In [89]:
np.ones((4,5,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])