### NUMPY

In [3]:
import numpy as np


In [4]:
np.array(["mario",2,3])  # List to array

array(['mario', '2', '3'], dtype='<U5')

In [6]:
np.array([[1,2],[3,4]])  # array[[i1,j1][i2,j2]] 2D

array([[1, 2],
       [3, 4]])

In [8]:
np.array([1,2,3], ndmin=5)  # 5D array

array([[[[[1, 2, 3]]]]])

In [9]:
np.array([1,2,3], dtype=complex)  # dtype

array([1.+0.j, 2.+0.j, 3.+0.j])

In [10]:
np.array([(1,2),(3,4)],dtype=[('a','<i2'),('b','<i8')])  # list of tuples into an array (a,b)

array([(1, 2), (3, 4)], dtype=[('a', '<i2'), ('b', '<i8')])